import s0 from "../../../public/devices/extension/blocked.webp";
import s1 from "../../../public/devices/extension/dashboard.webp";
import s2 from "../../../public/devices/extension/limits.webp";
import s3 from "../../../public/devices/extension/strict.webp";
import s4 from "../../../public/devices/ios/interrupt.webp";

import type { ScreenAsset } from "./types";

/**
 * GENERATED by scripts/import-screenshots.mjs — do not edit by hand.
 * Run `npm run screenshots` after adding files to design/screenshots/.
 *
 * Screens with a single entry are language-agnostic; screens with { es, en }
 * have one capture per locale.
 */
export const SCREENS = {
  extension: {
    blocked: s0 as ScreenAsset,
    dashboard: s1 as ScreenAsset,
    limits: s2 as ScreenAsset,
    strict: s3 as ScreenAsset,
  },
  ios: {
    interrupt: s4 as ScreenAsset,
  },
} as const;
